name: flutter_image_compress
description: compress image with native code(objc kotlin), it's faster. This library can work on android/ios.
version: 0.6.5+1
author: caijinglong<cjl_spy@163.com>
homepage: https://github.com/OpenFlutter/flutter_image_compress

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.example.flutterimagecompress
    pluginClass: FlutterImageCompressPlugin
